### PR TITLE
Adding barrel HCAL STEP, FreeCAD and gdml files

### PR DESCRIPTION
**Pull request by johnlajoie**
### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [X] New feature (issue #562 in epic, https://github.com/eic/epic/issues/562)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No breaking changes, just adding the files to the guthub repc

### Does this PR change default behavior?
No, not by itself.  This will enable changes

### CODE REVIEW

**Comment by veprbl** [comment]
The current GDML file is not a very useful one. It contains only a single tesselated solid for the whole detector.

**Comment by johnlajoie** [comment]
That was the point Dmitry - there is absolutely no point at all in regenerating the outer HCAL steel structure in code as we were doing before, it's error prone and difficult to maintain.  Rather that have meshes for the individuals parts, and then try to build the barrel in software, this is one mesh for the whole structure. Note that the STEP file and FreeCAD project that were used to general the GDML mesh file is also included for archival purposes, in case this ever needs to be revisited.

**Comment by veprbl** [comment]
How are you going to assign sensitive volume IDs?

**Comment by veprbl** [comment]
Okay, I'm told it's only absorbers here. Everything looks good then.

**Review by veprbl — APPROVED** [review]

**Comment by johnlajoie** [comment]
Yeah - it's just the absorbers. The tile meshes are very small, still in the xml file, and those are the sensitive volumes.  Sorry, I should have been more clear.

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
